server:
  port: 8088
  
spring:  h2:    console:
      enabled: true  datasource:    url: jdbc:h2:mem:dbActivity
    username: secure
    password: secure
  jpa:    database-platform: org.hibernate.dialect.H2Dialect 
    
    
eureka:
  instance:
    instance-id: ${spring.application.name}.${random.int}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka  
      
management:
  endpoints:
    web:
      exposure:
        include: "*"  