DROP TABLE IF EXISTS CONVERSION_DETAILS;

CREATE TABLE CONVERSION_DETAILS ( id INT AUTO_INCREMENT PRIMARY KEY, country_code CHAR(3) NOT NULL, conversion_factor decimal(30,3) NOT NULL);  
INSERT INTO CONVERSION_DETAILS (country_code,conversion_factor) VALUES
('USD',65), 
('EUR',75),  
('AUD',25);  
